# fly.toml app configuration file generated for m11-backend on 2024-01-12T18:22:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "m11-backend"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  destination = "/pb/pb_data"
  source = "m11_pb_data"